#!bash
OUTPUT_FILE=a.out
if [[ $2 != "" ]];then
  OUTPUT_FILE=$2
fi
if [[ -e $OUTPUT_FILE ]];then
  rm $OUTPUT_FILE -f
fi
if [[ ! -e $1 ]];then
  echo "usage:"
  echo "  jvavc [file] [output file]"
  exit
else
  touch $OUTPUT_FILE
fi
echo -e "\e[38;5;123mJvav 1.4"
echo -e "$(date)"
echo -e "Copyright 2022 Dr. HaoYang Zhang"
echo -e "Stay stupid,stay useless."
echo -e ""
echo -e "Compiling......"
echo -e ""
cat $1|while read i
do
  echo " + ${i}"
  sleep 0.2s
  COMMAND_CUT=$(echo $i|cut -d "[" -f 2 |cut -d ']' -f 1) >> /dev/null
  case $i in
    jvav.system.print*) echo "echo $COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.system.exit*) echo "exit $COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.system.sleep*) echo "sleep $COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.system.exec*) echo "$COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.system.get.file*) echo "cat $COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.system.get.time*) echo "date" >> $OUTPUT_FILE;;
    jvav.system.get.kernel*) echo  "uname --kernel-release" >> $OUTPUT_FILE;;
    jvav.system.get.arch*) echo  "uname -m" >> $OUTPUT_FILE;;
    jvav.system.get.hostname*) echo "hostname" >> $OUTPUT_FILE;;
    jvav.system.get.variable*) echo "echo \$$COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.system.create.variable*) echo "export $COMMAND_CUT" >> $OUTPUT_FILE;;
    jvav.clear*) echo "clear" >> $OUTPUT_FILE;;
    *) echo $i >> $OUTPUT_FILE
  esac
done
chmod 777 $OUTPUT_FILE
echo -e ""
echo -e "Compile done!"
